
name: junetech
description: Mobile app for JuneTech 5th Edition event management.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  http: ^1.1.0
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  flutter_animate: ^4.5.2
  dio: ^5.8.0+1
  dartz: ^0.10.1
  mobile_scanner: ^7.0.0
  awesome_snackbar_content: ^0.1.6
  hugeicons: ^0.0.11
  printing: ^5.14.2
  flutter_bluetooth_printer: ^2.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff" # Couleur de fond
  image: assets/images/splash.png # Chemin vers l'image
  android: true # Activer pour Android
  ios: true # Activer pour iOS
  fullscreen: true # Plein écran

flutter:
  uses-material-design: true
  assets:
    - assets/




